# Generated by Django 6.0.8 on 2026-08-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_passkeycredential'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='loginevent',
            index=models.Index(fields=['email', 'result', 'created_at'], name='accounts_lo_email_7d807c_idx'),
        ),
        migrations.AddIndex(
            model_name='loginevent',
            index=models.Index(fields=['ip_address', 'created_at'], name='accounts_lo_ip_addr_f490e1_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationchallenge',
            index=models.Index(fields=['user', 'channel', 'created_at'], name='accounts_ve_user_id_51709c_idx'),
        ),
    ]
