# Generated by Django 6.0.8 on 2026-08-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_loginevent_accounts_lo_email_7d807c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationchallenge',
            name='destination_masked',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='verificationchallenge',
            name='max_attempts',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='verificationchallenge',
            name='purpose',
            field=models.CharField(choices=[('verification', 'Contact verification'), ('authentication', 'Login'), ('security_action', 'Security change')], default='verification', max_length=20),
        ),
        migrations.AddField(
            model_name='verificationchallenge',
            name='request_id',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddIndex(
            model_name='verificationchallenge',
            index=models.Index(fields=['user', 'purpose', 'created_at'], name='accounts_ve_user_id_73d9dc_idx'),
        ),
    ]
