# Generated by Django 6.0.8 on 2026-08-17 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_verificationchallenge_destination_masked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpin_hash', models.CharField(blank=True, max_length=255)),
                ('mpin_enabled', models.BooleanField(default=False)),
                ('mpin_created_at', models.DateTimeField(blank=True, null=True)),
                ('mpin_changed_at', models.DateTimeField(blank=True, null=True)),
                ('mpin_failed_attempts', models.PositiveSmallIntegerField(default=0)),
                ('mpin_locked_until', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_credential', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__email'],
            },
        ),
        migrations.CreateModel(
            name='RecoveryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=64, unique=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'used_at'], name='accounts_re_user_id_51e9a4_idx')],
            },
        ),
    ]
