# Generated by Django 6.0.8 on 2026-08-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['is_active'], name='catalog_bra_is_acti_0ff477_idx'),
        ),
        migrations.AddIndex(
            model_name='servicetype',
            index=models.Index(fields=['is_active'], name='catalog_ser_is_acti_bedd07_idx'),
        ),
        migrations.AddIndex(
            model_name='voucherproduct',
            index=models.Index(fields=['is_active', 'brand'], name='catalog_vou_is_acti_641985_idx'),
        ),
    ]
