# Generated by Django 6.0.8 on 2026-08-19 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notificationpreference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('recipient', models.EmailField(db_index=True, max_length=254)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('body_hash', models.CharField(blank=True, max_length=64)),
                ('template_key', models.CharField(db_index=True, max_length=64)),
                ('provider', models.CharField(default='ses', max_length=32)),
                ('provider_message_id', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('BOUNCED', 'Bounced')], db_index=True, default='QUEUED', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(db_index=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['recipient', 'status'], name='notificatio_recipie_d274b7_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'idempotency_key'), name='email_log_idem')],
            },
        ),
        migrations.CreateModel(
            name='SmsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('recipient', models.CharField(db_index=True, max_length=20)),
                ('body_preview', models.CharField(blank=True, max_length=160)),
                ('body_hash', models.CharField(blank=True, max_length=64)),
                ('template_key', models.CharField(db_index=True, max_length=64)),
                ('provider', models.CharField(default='kaleyra', max_length=32)),
                ('provider_message_id', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('BOUNCED', 'Bounced')], db_index=True, default='QUEUED', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(db_index=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['recipient', 'status'], name='notificatio_recipie_597db0_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'idempotency_key'), name='sms_log_idem')],
            },
        ),
    ]
