# Generated by Django 6.0.8 on 2026-08-19 04:54

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('merchants', '0003_encrypt_step_pii'),
        ('orders', '0002_paymentorder_orders_paym_status_668de5_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('review', 'Review'), ('approve', 'Approve'), ('reject', 'Reject'), ('request_changes', 'Request changes')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('level', models.PositiveIntegerField(default=1)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('unit_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fees', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-revision'],
            },
        ),
        migrations.AddField(
            model_name='orderevent',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='orderevent',
            name='request_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='orderevent',
            name='revision',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='revision',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under review'), ('CHANGES_REQUESTED', 'Changes requested'), ('APPROVED', 'Approved'), ('PAYMENT_PENDING', 'Payment pending'), ('PAYMENT_VERIFIED', 'Payment verified'), ('FULFILMENT_PENDING', 'Fulfilment pending'), ('FULFILLED', 'Fulfilled'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='paymentorder',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='order_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='paymentorder',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='order_subtotal_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='paymentorder',
            constraint=models.CheckConstraint(condition=models.Q(('fees__gte', 0)), name='order_fees_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='paymentorder',
            constraint=models.CheckConstraint(condition=models.Q(('tax__gte', 0)), name='order_tax_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='paymentorder',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='order_total_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='paymentorder',
            constraint=models.CheckConstraint(condition=models.Q(('total', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('subtotal'), '+', models.F('fees')), '+', models.F('tax')))), name='order_total_matches_parts'),
        ),
        migrations.AddField(
            model_name='approvaldecision',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvaldecision',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='orders.paymentorder'),
        ),
        migrations.AddField(
            model_name='orderrevision',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderrevision',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='orders.paymentorder'),
        ),
        migrations.AddField(
            model_name='orderrevision',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.voucherproduct'),
        ),
        migrations.AddField(
            model_name='approvaldecision',
            name='revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='orders.orderrevision'),
        ),
        migrations.AddConstraint(
            model_name='orderrevision',
            constraint=models.UniqueConstraint(fields=('order', 'revision'), name='unique_order_revision'),
        ),
        migrations.AddIndex(
            model_name='approvaldecision',
            index=models.Index(fields=['order', 'created_at'], name='orders_appr_order_i_e00423_idx'),
        ),
    ]
