# Generated by Django 6.0.8 on 2026-08-16 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(max_length=20, unique=True)),
                ('business_name', models.CharField(blank=True, max_length=200)),
                ('entity_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('PROPRIETORSHIP', 'Proprietorship'), ('PARTNERSHIP', 'Partnership'), ('LLP', 'LLP'), ('PRIVATE_LIMITED', 'Private Limited Company'), ('PUBLIC_LIMITED', 'Public Limited Company'), ('TRUST', 'Trust'), ('SOCIETY', 'Society'), ('HUF', 'HUF')], max_length=30)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending review'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('kyc_status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('ACTION_REQUIRED', 'Action required'), ('REJECTED', 'Rejected')], default='NOT_STARTED', max_length=20)),
                ('kyb_status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('ACTION_REQUIRED', 'Action required'), ('REJECTED', 'Rejected')], default='NOT_STARTED', max_length=20)),
                ('bank_status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('ACTION_REQUIRED', 'Action required'), ('REJECTED', 'Rejected')], default='NOT_STARTED', max_length=20)),
                ('agreement_status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('ACTION_REQUIRED', 'Action required'), ('REJECTED', 'Rejected')], default='NOT_STARTED', max_length=20)),
                ('risk_status', models.CharField(choices=[('CLEAR', 'Clear'), ('REVIEW', 'Review'), ('HIGH', 'High')], default='CLEAR', max_length=20)),
                ('commercial_status', models.CharField(choices=[('INACTIVE', 'Inactive'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], default='INACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('assigned_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='access.department')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_merchants', to=settings.AUTH_USER_MODEL)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='merchant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BeneficialOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('role', models.CharField(blank=True, max_length=80)),
                ('ownership_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pan', models.CharField(blank=True, max_length=10)),
                ('is_authorized_signatory', models.BooleanField(default=False)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='merchants.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='OnboardingApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under review'), ('CLARIFICATION_REQUIRED', 'Clarification required'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=30)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=80)),
                ('rejection_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='merchants.merchant')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=80)),
                ('position', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('IN_PROGRESS', 'In progress'), ('COMPLETE', 'Complete'), ('NEEDS_CORRECTION', 'Needs correction'), ('LOCKED', 'Locked'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NOT_STARTED', max_length=30)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('clarification_message', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='merchants.onboardingapplication')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('application', 'key')},
            },
        ),
    ]
