# Generated by Django 6.0.8 on 2026-08-17 15:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficialowner',
            name='pan',
        ),
        migrations.AddField(
            model_name='beneficialowner',
            name='pan_encrypted',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='beneficialowner',
            name='pan_last4',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddIndex(
            model_name='onboardingapplication',
            index=models.Index(fields=['status', 'created_at'], name='merchants_o_status_557b5c_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingapplication',
            index=models.Index(fields=['merchant', 'created_at'], name='merchants_o_merchan_76bfcf_idx'),
        ),
    ]
