# Generated by Django 6.0.8 on 2026-08-16 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(max_length=20, unique=True)),
                ('version', models.CharField(default='1.0', max_length=10)),
                ('status', models.CharField(choices=[('GENERATED', 'Generated'), ('INTERNAL_REVIEW', 'Internal review'), ('MERCHANT_REVIEW', 'Merchant review'), ('MERCHANT_SIGNED', 'Merchant signed'), ('COUNTERSIGNED', 'Countersigned'), ('EXECUTED', 'Executed')], default='GENERATED', max_length=20)),
                ('body', models.TextField()),
                ('document_hash', models.CharField(blank=True, max_length=64)),
                ('generated_from', models.JSONField(blank=True, default=dict)),
                ('merchant_signed_at', models.DateTimeField(blank=True, null=True)),
                ('countersigned_at', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='merchants.merchant')),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
