# Generated by Django 6.0.8 on 2026-08-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0002_esign'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='template_version',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
