# Generated by Django 6.0.8 on 2026-08-17 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0003_agreement_template_version'),
        ('merchants', '0003_encrypt_step_pii'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgreementEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=40)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='agreement',
            name='document_file',
            field=models.FileField(blank=True, upload_to='agreements/source/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='esign_verification_id',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='agreement',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='signed_document_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='agreement',
            name='signed_file',
            field=models.FileField(blank=True, upload_to='agreements/signed/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='status',
            field=models.CharField(choices=[('GENERATED', 'Generated'), ('INTERNAL_REVIEW', 'Internal review'), ('MERCHANT_REVIEW', 'Merchant review'), ('MERCHANT_SIGNED', 'Merchant signed'), ('COUNTERSIGNED', 'Countersigned'), ('EXECUTED', 'Executed'), ('EXPIRED', 'Expired'), ('SIGNING_FAILED', 'Signing failed'), ('CANCELLED', 'Cancelled')], default='GENERATED', max_length=20),
        ),
        migrations.AddIndex(
            model_name='agreement',
            index=models.Index(fields=['status', 'created_at'], name='agreements__status_9db6f9_idx'),
        ),
        migrations.AddIndex(
            model_name='agreement',
            index=models.Index(fields=['merchant', 'status'], name='agreements__merchan_60821c_idx'),
        ),
        migrations.AddField(
            model_name='agreementevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agreementevent',
            name='agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='agreements.agreement'),
        ),
        migrations.AddIndex(
            model_name='agreementevent',
            index=models.Index(fields=['agreement', 'created_at'], name='agreements__agreeme_55e546_idx'),
        ),
    ]
