# Generated by Django 6.0.8 on 2026-08-16 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder', models.CharField(max_length=150)),
                ('ifsc', models.CharField(max_length=11)),
                ('account_number_encrypted', models.TextField()),
                ('verified', models.BooleanField(default=False)),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to='merchants.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(max_length=20, unique=True)),
                ('doc_type', models.CharField(choices=[('PAN', 'PAN Card'), ('GST', 'GST Certificate'), ('COI', 'Certificate of Incorporation'), ('BANK_PROOF', 'Bank Proof'), ('OTHER', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('UNDER_REVIEW', 'Under review'), ('VERIFIED', 'Verified'), ('ACTION_REQUIRED', 'Action required'), ('REJECTED', 'Rejected')], default='UPLOADED', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='merchants.merchant')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
