# Generated by Django 6.0.8 on 2026-08-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0002_identity_and_document_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('PAN', 'PAN Card'), ('GST', 'GST Certificate'), ('AADHAAR', 'Aadhaar'), ('COI', 'Certificate of Incorporation'), ('BANK_PROOF', 'Bank Proof'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='identitycheck',
            name='kind',
            field=models.CharField(choices=[('PAN', 'PAN'), ('GSTIN', 'GSTIN'), ('AADHAAR', 'Aadhaar'), ('BANK', 'Bank account'), ('CIN', 'CIN')], max_length=20),
        ),
        migrations.AlterField(
            model_name='identitycheck',
            name='status',
            field=models.CharField(choices=[('MATCH', 'Match'), ('MISMATCH', 'Mismatch'), ('PENDING', 'Pending'), ('ERROR', 'Error')], max_length=20),
        ),
    ]
