# Generated by Django 6.0.8 on 2026-08-17 15:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0002_remove_beneficialowner_pan_and_more'),
        ('verification', '0003_alter_document_doc_type_alter_identitycheck_kind_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['merchant', 'status'], name='verificatio_merchan_b5ddbf_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['doc_type', 'status'], name='verificatio_doc_typ_46c374_idx'),
        ),
    ]
