# Generated by Django 6.0.8 on 2026-08-17 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0003_encrypt_step_pii'),
        ('verification', '0004_document_verificatio_merchan_b5ddbf_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('aadhaar_verification', 'Aadhaar verification'), ('digilocker_access', 'DigiLocker access'), ('esign', 'Aadhaar eSign'), ('kyc', 'KYC processing')], max_length=30)),
                ('consent_text_version', models.CharField(max_length=20)),
                ('consent_given', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(default='portal', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'purpose', 'created_at'], name='verificatio_user_id_014ef3_idx')],
            },
        ),
        migrations.CreateModel(
            name='VerificationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(max_length=20, unique=True)),
                ('verification_type', models.CharField(choices=[('PAN', 'PAN'), ('AADHAAR', 'Aadhaar'), ('GSTIN', 'GSTIN'), ('BANK_ACCOUNT', 'Bank account'), ('IFSC', 'IFSC'), ('CIN', 'CIN'), ('NAME_MATCH', 'Name match'), ('DIGILOCKER', 'DigiLocker')], max_length=20)),
                ('provider', models.CharField(default='cashfree', max_length=20)),
                ('verification_id', models.CharField(max_length=50, unique=True)),
                ('reference_id', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('VERIFIED', 'Verified'), ('PARTIALLY_VERIFIED', 'Partially verified'), ('FAILED', 'Failed'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('REQUIRES_ACTION', 'Requires action'), ('REQUIRES_RETRY', 'Requires retry')], default='PENDING', max_length=20)),
                ('sub_status', models.CharField(blank=True, max_length=60)),
                ('document_hash', models.CharField(db_index=True, max_length=64)),
                ('document_encrypted', models.TextField(blank=True)),
                ('document_masked', models.CharField(blank=True, max_length=40)),
                ('verified_name', models.CharField(blank=True, max_length=150)),
                ('verified_dob', models.CharField(blank=True, max_length=10)),
                ('verified_gender', models.CharField(blank=True, max_length=10)),
                ('verified_address', models.TextField(blank=True)),
                ('verified_state', models.CharField(blank=True, max_length=60)),
                ('verified_city', models.CharField(blank=True, max_length=60)),
                ('verified_district', models.CharField(blank=True, max_length=60)),
                ('verified_pincode', models.CharField(blank=True, max_length=6)),
                ('verified_data_encrypted', models.TextField(blank=True)),
                ('provider_response_encrypted', models.TextField(blank=True)),
                ('name_match_score', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('name_match_category', models.CharField(blank=True, max_length=30)),
                ('failure_reason', models.CharField(blank=True, max_length=200)),
                ('attempt_count', models.PositiveSmallIntegerField(default=1)),
                ('reuse_reason', models.CharField(blank=True, max_length=60)),
                ('reused_at', models.DateTimeField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_records', to='merchants.merchant')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verification_records', to=settings.AUTH_USER_MODEL)),
                ('reused_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reuses', to='verification.verificationrecord')),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['verification_type', 'document_hash'], name='verificatio_verific_9b2800_idx'), models.Index(fields=['merchant', 'verification_type'], name='verificatio_merchan_05aa00_idx'), models.Index(fields=['requested_by', 'verification_type'], name='verificatio_request_8edfca_idx'), models.Index(fields=['reference_id'], name='verificatio_referen_a8eb2e_idx'), models.Index(fields=['status', 'requested_at'], name='verificatio_status_acadf6_idx'), models.Index(fields=['expires_at'], name='verificatio_expires_0edb7d_idx')],
            },
        ),
    ]
