# Generated by Django 6.0.8 on 2026-09-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0005_consentrecord_verificationrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='slot_id',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('PAN', 'PAN Card'), ('GST', 'GST Certificate'), ('AADHAAR', 'Aadhaar'), ('COI', 'Certificate of Incorporation'), ('BANK_PROOF', 'Bank Proof'), ('MOA', 'Memorandum of Association'), ('AOA', 'Articles of Association'), ('BOARD_RESOLUTION', 'Board Resolution'), ('AUTH_LETTER', 'Letter of Authority'), ('TRUSTEE_RESOLUTION', 'Trustee Resolution'), ('PARTNERSHIP_DEED', 'Partnership Deed'), ('TRUST_DEED', 'Trust / Society Deed'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='verificationrecord',
            name='verification_type',
            field=models.CharField(choices=[('PAN', 'PAN'), ('AADHAAR', 'Aadhaar'), ('GSTIN', 'GSTIN'), ('BANK_ACCOUNT', 'Bank account'), ('IFSC', 'IFSC'), ('CIN', 'CIN'), ('UDYAM', 'Udyam'), ('NAME_MATCH', 'Name match'), ('DIGILOCKER', 'DigiLocker')], max_length=20),
        ),
    ]
