from django.urls import path
from django.views.generic import RedirectView

from portals.views.administration import (
    AdminDashboardView,
    AdminVerificationDashboardView,
    AuditListView,
    DocumentReviewView,
    EmployeeListView,
    EmployeeRoleView,
    MerchantDetailView,
    MerchantListView,
    OnboardingQueueView,
    OrderListView,
    SecurityCenterView,
)
from portals.views.auth import (
    LoginRedirectView,
    MerchantRegisterView,
)
from portals.views.common import (
    AccountProfileView,
    AgreementDownloadView,
    DocumentDownloadView,
    MfaChallengeView,
    MfaSetupView,
    NotificationListView,
    OrderDocumentView,
    SearchView,
    SecurityActionView,
    SecurityCenterAccountView,
    SessionListView,
    VerifyEmailView,
    VerifyMobileView,
)
from portals.views.employee import (
    EmployeeApplicationView,
    EmployeeDashboardView,
    EmployeeOrderView,
    EmployeeQueueView,
)
from portals.views.merchant import (
    MerchantAgreementView,
    MerchantDashboardView,
    MerchantDocumentView,
    MerchantOrderCreateView,
    MerchantOrderDetailView,
    MerchantOrderListView,
    MerchantPincodeLookupView,
    MerchantProfileView,
    MerchantVerificationCenterView,
    OnboardingDetailView,
    OnboardingStartView,
)
from portals.views.reports import (
    AdminRoleView,
    EmployeeOrderListView,
)

administration_patterns = [
    path("login/", LoginRedirectView.as_view(), name="login"),
    path("logout/", RedirectView.as_view(url="/logout/", permanent=False), name="logout"),
    path("", AdminDashboardView.as_view(), name="dashboard"),
    path("merchants/", MerchantListView.as_view(), name="merchants"),
    path("verification/", AdminVerificationDashboardView.as_view(), name="verification"),
    path("merchants/<str:public_id>/", MerchantDetailView.as_view(), name="merchant_detail"),
    path("onboarding/", OnboardingQueueView.as_view(), name="onboarding"),
    path("orders/", OrderListView.as_view(), name="orders"),
    path("employees/", EmployeeListView.as_view(), name="employees"),
    path("employees/<int:user_id>/role/", EmployeeRoleView.as_view(), name="employee_role"),
    path("roles/", AdminRoleView.as_view(), name="roles"),
    path("audit/", AuditListView.as_view(), name="audit"),
    path("security/", SecurityCenterView.as_view(), name="security"),
    path("security/users/<int:user_id>/", SecurityActionView.as_view(), name="security_action"),
    path("documents/<str:public_id>/", DocumentReviewView.as_view(), name="document_review"),
    path("documents/<str:public_id>/download/", DocumentDownloadView.as_view(), name="document_download"),
    path("notifications/", NotificationListView.as_view(), name="notifications"),
    path("search/", SearchView.as_view(), name="search"),
    path("mfa/", MfaChallengeView.as_view(), name="mfa"),
    path("mfa/setup/", MfaSetupView.as_view(), name="mfa_setup"),
    path("sessions/", SessionListView.as_view(), name="sessions"),
    path("account/profile/", AccountProfileView.as_view(), name="account_profile"),
    path("account/security/", SecurityCenterAccountView.as_view(), name="account_security"),
]

employee_patterns = [
    path("login/", LoginRedirectView.as_view(), name="login"),
    path("logout/", RedirectView.as_view(url="/logout/", permanent=False), name="logout"),
    path("", EmployeeDashboardView.as_view(), name="dashboard"),
    path("queue/", EmployeeQueueView.as_view(), name="queue"),
    path("queue/<str:public_id>/", EmployeeApplicationView.as_view(), name="application"),
    path("orders/", EmployeeOrderListView.as_view(), name="orders"),
    path("orders/<str:public_id>/", EmployeeOrderView.as_view(), name="order"),
    path("orders/<str:public_id>/document/", OrderDocumentView.as_view(), name="order_document"),
    path("profile/", AccountProfileView.as_view(), name="profile"),
    path("notifications/", NotificationListView.as_view(), name="notifications"),
    path("search/", SearchView.as_view(), name="search"),
    path("mfa/", MfaChallengeView.as_view(), name="mfa"),
    path("mfa/setup/", MfaSetupView.as_view(), name="mfa_setup"),
    path("sessions/", SessionListView.as_view(), name="sessions"),
    path("account/security/", SecurityCenterAccountView.as_view(), name="account_security"),
]

merchant_patterns = [
    path("login/", LoginRedirectView.as_view(), name="login"),
    path("logout/", RedirectView.as_view(url="/logout/", permanent=False), name="logout"),
    path("register/", MerchantRegisterView.as_view(), name="register"),
    path("", MerchantDashboardView.as_view(), name="dashboard"),
    path("onboarding/", OnboardingStartView.as_view(), name="onboarding"),
    path("onboarding/pincode/", MerchantPincodeLookupView.as_view(), name="pincode_lookup"),
    path("onboarding/<str:public_id>/", OnboardingDetailView.as_view(), name="onboarding_detail"),
    path("orders/", MerchantOrderListView.as_view(), name="orders"),
    path("orders/new/", MerchantOrderCreateView.as_view(), name="order_create"),
    path("orders/<str:public_id>/", MerchantOrderDetailView.as_view(), name="order_detail"),
    path("orders/<str:public_id>/document/", OrderDocumentView.as_view(), name="order_document"),
    path("agreements/", MerchantAgreementView.as_view(), name="agreements"),
    path("agreements/<str:public_id>/download/", AgreementDownloadView.as_view(), name="agreement_download"),
    path("verification/", MerchantVerificationCenterView.as_view(), name="verification"),
    path("documents/", MerchantDocumentView.as_view(), name="documents"),
    path("documents/<str:public_id>/download/", DocumentDownloadView.as_view(), name="document_download"),
    path("profile/", MerchantProfileView.as_view(), name="profile"),
    path("notifications/", NotificationListView.as_view(), name="notifications"),
    path("search/", SearchView.as_view(), name="search"),
    path("verify/email/", VerifyEmailView.as_view(), name="verify_email"),
    path("verify/mobile/", VerifyMobileView.as_view(), name="verify_mobile"),
    path("mfa/", MfaChallengeView.as_view(), name="mfa"),
    path("mfa/setup/", MfaSetupView.as_view(), name="mfa_setup"),
    path("sessions/", SessionListView.as_view(), name="sessions"),
    path("account/security/", SecurityCenterAccountView.as_view(), name="account_security"),
]
