# Generated by Django 6.0.8 on 2026-08-17 15:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_publicidsequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['resource_type', 'resource_id'], name='audit_audit_resourc_2ab5ff_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['request_id'], name='audit_audit_request_c59dc1_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['created_at'], name='audit_audit_created_7710b7_idx'),
        ),
    ]
