# Generated by Django 6.0.3 on 2026-08-19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("audit", "0003_auditevent_user_agent_and_more")]

    operations = [
        migrations.CreateModel(
            name="ApiCallLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider", models.CharField(max_length=100)),
                ("method", models.CharField(max_length=10)),
                ("endpoint", models.CharField(max_length=255)),
                ("status_code", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("success", models.BooleanField(default=False)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("error_type", models.CharField(blank=True, max_length=80)),
                ("request_id", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(model_name="apicalllog", index=models.Index(fields=["provider", "created_at"], name="audit_apica_provide_940e7c_idx")),
        migrations.AddIndex(model_name="apicalllog", index=models.Index(fields=["success", "created_at"], name="audit_apica_success_248774_idx")),
        migrations.AddIndex(model_name="apicalllog", index=models.Index(fields=["request_id"], name="audit_apica_request_d282dd_idx")),
    ]
